base_url : "https://api-tryqa.onrender.com/"
JSON_FILE : "data/registered_users.json"
EXCEL_FILE_1 : "data/register_user.xlsx"
YAML_FILE   : "data/register_user.yaml"
sauce_url : "https://www.saucedemo.com/"
flipkart_url: "https://www.flipkart.com/"